version: '3.10'

services:
  client:
    image: node:20
#        npm run dev -- --host 0.0.0.0 --port 8080 &&
    command: >
      bash -c "
        echo 'Trying to install/update dependencies in case of architecture missmatch...' &&
        npm ci &&
        npm run dev -- --host 0.0.0.0 --port 8080
      "
    working_dir: /src/www/apps/client
    environment:
      VITE_SERVER_URL: http://localhost:${SERVER_PORT:-3000}
    ports:
      - ${CLIENT_PORT:-8080}:8080
    volumes:
      - ./apps/client:/src/www/apps/client
      - ./packages:/src/www/packages

  server:
    image: node:20
    command: sh server_start.sh
    working_dir: /src/www/apps/server
    environment:
      MONGO_URL: mongodb://root:root@db:27017/smart?authSource=admin
    ports:
      - ${SERVER_PORT:-3000}:3000
    volumes:
      - ./apps/server:/src/www/apps/server
      - ./packages:/src/www/packages

  db:
    image: mongo:7.0
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: smart

  db-web:
    image: mongo-express
    depends_on:
      - db
    ports:
      - ${DB_WEB:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/

volumes:
  data:
