name: Server

on:
  pull_request:
    paths:
      - apps/server/**
      - packages/common/**
      - .github/workflows/server.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  APP: server

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #         cache-dependency-path: ./apps/${{env.APP}}/package-lock.json
  #     - name: Install dependencies
  #       run: npm ci
  #       working-directory: ./apps/${{env.APP}}
  #     - name: Lint
  #       run: npm run lint
  #       working-directory: ./apps/${{env.APP}}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./apps/${{env.APP}}/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./apps/${{env.APP}}
      # - name: Test
      #   run: npm test
      #   working-directory: ./apps/${{env.APP}}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        working-directory: ./apps/${{env.APP}}
        with:
          name: Tests            # Name of the check run which will be created
          path: junit.xml
          reporter: jest-junit